.TH man 3 "$BUILD_DATE" "$VERSION" "glee man page"

.SH NAME
glee \- media file player

.SH SYNOPSIS
.nf
glee_dir add PATH_TO_DIRECTORY
glee_dir list [--keyword, -k KEYWORD] [--page, -p PAGE]
glee_dir scan DIRECTORY_ID
glee_dir del DIRECTORY_ID

glee_file list [--keyword, -k KEYWORD] [--page, -p PAGE]
glee_file play FILE_ID

glee_master play [--keyword, -k KEYWORD] [--limit, -p LIMIT]
.sp

.SH DESCRIPTION
.B
glee_dir
is use to manage media directory by adding, scanning or deleting a directory
from database.

.B
glee_file
is use to retrieve files which indexed by
.B
glee_dir
and play specific media file by VLC.

.B
glee_master
is use to auto play media files in case you do something and want to glee
chooses media files.

.SH EXAMPLES
See /usr/share/doc/glee/usage.txt

.SH FILES
.TP 4
/usr/lib/libglee_*.so
Dynamic library of glee.

.TP
/usr/bin/glee_*
Executable file of glee.

.TP
/usr/share/man/man3/glee.3.gz
Manual file.

.TP
/usr/share/doc/glee/*.txt
Document files.

.SH REFERENCES 
Development repository at https://github.com/kevin-leptons/glee

.SH AUTHORS
Kevin Leptons <kevin.leptons@gmail.com>
